spring:
  flyway:
    locations: classpath:/db/migration/postgres
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/school
    username: postgres
    password: 1234
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
