DROP SCHEMA school CASCADE;
CREATE SCHEMA school;

-- TRUNCATE school.students RESTART IDENTITY CASCADE IF EXISTS school;
-- TRUNCATE school.courses RESTART IDENTITY CASCADE;
-- TRUNCATE school.students_courses_relation RESTART IDENTITY CASCADE;
